apiVersion: v1
data:
  APP_PROTOCOL_VERSION: 100350/6ec8E598962F1f475504F82fD5bF3410eAE58B9B/MEQCIDDOJNura6Q1d+t9TSB+l5CvRA659xW9YgdbTOQXikgeAiA.p0GML4WK8FVRBeHKnrLHRrgOWZl1rzk8.IZY0U8cog==/ZHU4OmxhdW5jaGVydTQyOjEvYzExOGQ2Njg1MWQyYzI2MWY0YjNkMmIzMzMxODE0ODFkMGZmOWVkOHU2OnBsYXllcnU0MjoyLzFlY2M4N2Y5NTUxODQ3NTc2NzIyM2M5YThkNWMzNzNmODdkMWExOWF1OTp0aW1lc3RhbXB1MTA6MjAyMi0xMi0yN2U=
kind: ConfigMap
metadata:
  name: version-config
