apiVersion: v1
data:
  APP_PROTOCOL_VERSION: 100330/6ec8E598962F1f475504F82fD5bF3410eAE58B9B/MEUCIQDf4N+cEa.VdRRpY9SnkjNitKRwves0lJuO0hr3xjir+AIgYRh8NrvlnNe90Es.hSmf3ruVIZWEjVuZufcSSQ1Fcwk=/ZHU4OmxhdW5jaGVydTQyOjUvNDgyNGRhYTk4MmFkNjJhMWY0MjY4MmIyNmE0ZDkzNjNhMzk5NGZlN3U2OnBsYXllcnU0MjoxL2M5ZmZiYWQ3MGUxNTEwYmJjNDAxOWNmMWQ2Yjc2OTQxNGM4M2I4MDF1OTp0aW1lc3RhbXB1MTA6MjAyMi0xMi0wNWU=
kind: ConfigMap
metadata:
  name: version-config
