apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: data-provider-db
  name: data-provider-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-provider-db
  serviceName: data-provider-db
  template:
    metadata:
      labels:
        app: data-provider-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: dp
            - name: MYSQL_ROOT_PASSWORD
              value: dp-pw
          image: mysql:8.0.30
          name: data-provider-db
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data-provider-db-data
      restartPolicy: Always
  updateStrategy:
    type: OnDelete      
  volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        name: data-provider-db-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: gp2
        volumeMode: Filesystem
