apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    labels:
      app: explorer
    name: explorer
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: explorer
    serviceName: explorer
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: explorer
      spec:
        initContainers:
        - args:
          - sleep 60
          command:
          - /bin/sh
          - -c
          image: nginx
          name: wait-for-miner
        containers:
        - args:
          - NineChronicles.Headless.Executable.dll
          - run
          - --workers=500
          - --app-protocol-version=1067/8c72600A23ed14026ab76d56B9A0edc339B305B0/MEUCIQDBsAhBgWjwg91M9miBpA+XjX2hQMdk8PvGa9ZN8QsskgIgJ73BV+Y0Lj+8aXZH.S36KC2tO2CdxdTOnMw6OvWbuHc=/ZHUxNjpXaW5kb3dzQmluYXJ5VXJsdTY1Omh0dHBzOi8vZG93bmxvYWQubmluZS1jaHJvbmljbGVzLmNvbS9wcmV2aWV3bmV0L3YxMDY3L1dpbmRvd3MuemlwdTk6dGltZXN0YW1wdTEwOjIwMjItMDYtMTZl
          - --trusted-app-protocol-version-signer=02182d2d97a0cbc56c84b3eff293ca3aadc3baab6e3bc1359c0c93d0ab4eb0d1d9
          - --genesis-block-path=https://9c-test.s3.ap-northeast-2.amazonaws.com/genesis-block-rune
          - --store-path=/data/explorer
          - --store-type=rocksdb
          - --ice-server=turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us.planetarium.dev:3478
          - --peer
          - 027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,9c-previewnet-tcp.planetarium.dev,31236
          - --graphql-server
          - --graphql-host=0.0.0.0
          - --graphql-port=31235
          - --no-cors
          - --network-type=default
          command:
          - dotnet
          image: kustomization-ninechronicles-headless
          imagePullPolicy: IfNotPresent
          env:
          - name: APP_PROTOCOL_VERSION_KEY
            valueFrom:
              configMapKeyRef:
                name: version-config
                key: APP_PROTOCOL_VERSION
          name: explorer-test
          ports:
          - containerPort: 31235
            name: explorer
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: explorer-data
        dnsPolicy: ClusterFirst
        nodeSelector:
          alpha.eksctl.io/nodegroup-name: 9c-previewnet
          beta.kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    volumeClaimTemplates:
    - metadata:
        name: explorer-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: gp2
        volumeMode: Filesystem
kind: List
metadata:
  resourceVersion: ''
  selfLink: ''
