apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: previewnet-miner-1
  name: previewnet-miner-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: previewnet-miner-1
  serviceName: previewnet-miner-1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: previewnet-miner-1
    spec:
      containers:
      - args:
        - NineChronicles.Headless.Executable.dll
        - run
        - --workers=500
        - --app-protocol-version=$(APP_PROTOCOL_VERSION_KEY)
        - --trusted-app-protocol-version-signer=02182d2d97a0cbc56c84b3eff293ca3aadc3baab6e3bc1359c0c93d0ab4eb0d1d9
        - --genesis-block-path=https://9c-test.s3.ap-northeast-2.amazonaws.com/genesis-block-rune
        - --store-path=/data/miner
        - --store-type=rocksdb
        - --ice-server=turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us.planetarium.dev:3478
        - --peer
        - 027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,9c-previewnet-tcp.planetarium.dev,31236
        - --miner-private-key
        - $(PRIVATE_KEY)
        - --swarm-private-key
        - $(PRIVATE_KEY)
        - --graphql-server
        - --graphql-port=80
        - --network-type=default
        - --no-miner=false
        command:
        - dotnet
        image: kustomization-ninechronicles-headless
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_PROTOCOL_VERSION_KEY
          valueFrom:
            configMapKeyRef:
              name: version-config
              key: APP_PROTOCOL_VERSION
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: miner-keys
              key: miner1
        name: previewnet-miner-1
        ports:
        - containerPort: 80
          name: graphql
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: previewnet-miner-1-data
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: acr-regcred
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: 9c-previewnet
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: previewnet-miner-1-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          cpu: 1500m
          memory: 6Gi
          storage: 100Gi
      storageClassName: gp2
      volumeMode: Filesystem
