apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: remote-headless-1
  name: remote-headless-1
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: remote-headless-1
  serviceName: remote-headless-1
  template:
    metadata:
      labels:
        app: remote-headless-1
    spec:
      initContainers:
      - args:
        - sleep 60
        command:
        - /bin/sh
        - -c
        image: nginx
        name: wait-for-miner
      containers:
      - args:
        - NineChronicles.Headless.Executable.dll
        - run
        - --workers=500
        - --app-protocol-version=$(APP_PROTOCOL_VERSION_KEY)
        - --trusted-app-protocol-version-signer=02182d2d97a0cbc56c84b3eff293ca3aadc3baab6e3bc1359c0c93d0ab4eb0d1d9
        - --genesis-block-path=https://9c-test.s3.ap-northeast-2.amazonaws.com/genesis-block-rune
        - --store-path=/data/headless
        - --store-type=rocksdb
        - --ice-server=turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us.planetarium.dev:3478
        - --peer
        - 027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,9c-previewnet-tcp.planetarium.dev,31236
        - --no-miner
        - --graphql-server
        - --graphql-host=0.0.0.0
        - --graphql-port=80
        - --rpc-server
        - --rpc-remote-server
        - --rpc-listen-host=0.0.0.0
        - --rpc-listen-port=31238
        - --chain-tip-stale-behavior-type=reboot
        - --no-cors
        - --network-type=default
        command:
        - dotnet
        image: kustomization-ninechronicles-headless
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_PROTOCOL_VERSION_KEY
          valueFrom:
            configMapKeyRef:
              name: version-config
              key: APP_PROTOCOL_VERSION
        name: remote-headless-1
        ports:
        - containerPort: 80
          name: graphql
          protocol: TCP
        - containerPort: 31234
          name: headless
          protocol: TCP
        - containerPort: 31238
          name: rpc
          protocol: TCP
        resources:
          requests:
            cpu: 1300m
            memory: 5Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: remote-headless-1-data
      dnsPolicy: ClusterFirst
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: 9c-previewnet
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      name: remote-headless-1-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: gp2
      volumeMode: Filesystem
