apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: previewnet-seed-tcp
  name: previewnet-seed-tcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: previewnet-seed-tcp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: previewnet-seed-tcp
    spec:
      containers:
      - args:
        - Libplanet.Seed.Executable.dll
        - run
        - --log-level=debug
        - --app-protocol-version=$(APP_PROTOCOL_VERSION_KEY)
        - --host=9c-previewnet-tcp.planetarium.dev
        - --port=31236
        - --private-key=$(SEED_PRIVATE_KEY)
        - --graphql-host=0.0.0.0
        - --graphql-port=31237
        command:
        - dotnet
        image: planetariumhq/libplanet-seed:git-5fdbdf26412f61052daeaa2b54116391f93b58ef
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_PROTOCOL_VERSION_KEY
          valueFrom:
            configMapKeyRef:
              name: version-config
              key: APP_PROTOCOL_VERSION
        - name: SEED_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: seed1
              name: seed-keys
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 31236
          timeoutSeconds: 1
        name: seed
        ports:
        - containerPort: 31236
          name: node
          protocol: TCP
        - containerPort: 31237
          name: graphql
          protocol: TCP
        resources:
          requests:
            cpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: acr-regcred
      nodeSelector:
        beta.kubernetes.io/os: linux
        alpha.eksctl.io/nodegroup-name: 9c-previewnet
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
