apiVersion: v1
data:
  APP_PROTOCOL_VERSION: 1142/54684Ac4ee5B933e72144C4968BEa26056880d71/MEQCIBkPta0A.p6Ntervhj5JHv+FrB644ruQaOM2NyMi3H3RAiBr+E9djV48d6PUd7.v.izGLJVHFe2CVtGvrj6JdWe5eA==/ZHU4OmxhdW5jaGVydTQyOjEvMjVjYjY4MWI0NDcwZGYzNGNkODY3NGE0OTVmMGQ4NjAxZTI4YWYxOHU2OnBsYXllcnU0MjoxLzJiYzcwOTJhNzg5ODk3ZTg3ZTUwMzJjNWI1NzNiOGI5OWU3MTdhZDR1OTp0aW1lc3RhbXB1MTA6MjAyMi0xMi0xM2U=
kind: ConfigMap
metadata:
  name: version-config
