apiVersion: v1
data:
  APP_PROTOCOL_VERSION: 1146/54684Ac4ee5B933e72144C4968BEa26056880d71/MEUCIQDMgpddF7bKm9zjRtkyeK456jKK6lah+6EPi1m6FvspKgIgHFGODusduvjiVP8VoCP57rn1wWU7YidG2IlW0iAZmWU=/ZHU4OmxhdW5jaGVydTQyOjEvZTA1NGM1MGMxMDI2ODVmMzU0MzM5OWZkYzUwMTEzY2FhZjI4ZGVjZnU2OnBsYXllcnU0MjoxLzEwMDQ1ODlmZGEzYzEwYTg4NTQ4MjBkMzZhODMxYWUwNjE2NTk3ZTB1OTp0aW1lc3RhbXB1MTA6MjAyMi0xMi0xNWU=
kind: ConfigMap
metadata:
  name: version-config
