apiVersion: v1
data:
  APP_PROTOCOL_VERSION: 1148/54684Ac4ee5B933e72144C4968BEa26056880d71/MEQCICP4aU5vYwinVb7YJDGcSJ45viIYEXoCUOzlDjLQIn7ZAiAgRj7nfzgwA9JdVVkHErGr8j3ll5HeUz4AQzrWKhSEjQ==/ZHU4OmxhdW5jaGVydTQyOjEvZTA1NGM1MGMxMDI2ODVmMzU0MzM5OWZkYzUwMTEzY2FhZjI4ZGVjZnU2OnBsYXllcnU0MjoxLzBkYTQ0NjY3ZTQxNGMxZDVmZDFjZGY4MDZhMGQ5NTYyMDc5ZWVmZjV1OTp0aW1lc3RhbXB1MTA6MjAyMi0xMi0xNmU=
kind: ConfigMap
metadata:
  name: version-config
