apiVersion: v1
data:
  APP_PROTOCOL_VERSION: 1129/54684Ac4ee5B933e72144C4968BEa26056880d71/MEUCIQCIc7+JDWLDnc8jeLU70yDYEIwjVY58KxDP1Yu1XsZbBgIgKNW4cJkBpBtwtfY3WlR2b089Wy4NRLBTlUrsdgnx7yo=/ZHU4OmxhdW5jaGVydTQyOjEvZTAzNDUyOThjZDIzYzFiNjk1OTg1NzgzYTIzZTc0NjYwYTEzNDE5OXU2OnBsYXllcnU0MjoxL2YzMmZiOGI4NDI0NzM5M2EwMjg1Y2VmZWMyMGUyYTU0MmVmODUyMGR1OTp0aW1lc3RhbXB1MTA6MjAyMi0xMS0yM2U=
kind: ConfigMap
metadata:
  name: version-config
