apiVersion: v1
kind: Service
metadata:
  name: network-tcp
spec:
  ports:
  - name: node
    port: 31236
    targetPort: 31236
  - name: graphql
    port: 31237
    targetPort: 31237
  selector:
    app: internal-seed-tcp
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: network
spec:
  ports:
  - name: node
    port: 31236
    targetPort: 31236
  - name: graphql
    port: 31237
    targetPort: 31237
  selector:
    app: internal-seed
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: rpc
spec:
  ports:
  - port: 31233
    targetPort: 31233
  selector:
    app: internal-seed
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: explorer
spec:
  ports:
  - port: 31235
    targetPort: 31235
  selector:
    app: explorer
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: bridge-api-node
spec:
  clusterIP: None
  ports:
  - port: 31235
    name: graphql
    targetPort: 31235
  selector:
    app: bridge-api-node

---

apiVersion: v1
kind: Service
metadata:
  name: internal-miner-1
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  selector:
    app: internal-miner-1
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: internal-miner-2
spec:
  ports:
  - port: 80
    name: graphql
    targetPort: 80
  selector:
    app: internal-miner-2
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: remote-headless-1
spec:
  ports:
  - name: graphql
    port: 80
    targetPort: 80
  - name: rpc
    port: 31238
    targetPort: 31238
  - name: headless
    port: 31234
    targetPort: 31234
  selector:
    app: remote-headless-1
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: internal-data-provider
spec:
  ports:
    - name: headless
      port: 31234
      targetPort: 31234
    - name: graphql
      port: 80
      targetPort: 80
  selector:
    app: internal-data-provider
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: internal-data-provider-db
  name: internal-data-provider-db
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: internal-data-provider-db
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: internal-onboarding-redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: internal-onboarding-redis
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: internal-onboarding-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: internal-onboarding-db
  type: LoadBalancer


---

apiVersion: v1
kind: Service
metadata:
  name: internal-onboarding-app
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 5000
  selector:
    app: internal-onboarding-app
  type: LoadBalancer
