apiVersion: v1
data:
  APP_PROTOCOL_VERSION: 100302/54684Ac4ee5B933e72144C4968BEa26056880d71/MEQCIB+3E2jwI5YBCAXJnUUoi5tEBfhqFlPWCO4BtbSFvfLkAiBD2pqoFSQLUj3CEKccwCimXHYJ485SCfnDf3.ZWQ5UDQ==/ZHU4OmxhdW5jaGVydTQyOjIvMzdlZDY2ODFiNzgzMDllNTJhZjRhNDUxNTkwNzg4ZDI2MGQwZDFjZXU2OnBsYXllcnU0MjoyLzhiM2IxNWRjMTBiNjViZjY2MmQ3YjhiNTFjYWM0MjA4YmRiODVmMTF1OTp0aW1lc3RhbXB1MTA6MjAyMi0xMC0xOWU=
kind: ConfigMap
metadata:
  name: version-config
