apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    labels:
      app: explorer
      tags.datadoghq.com/env: explorer
      tags.datadoghq.com/version: '1'
    name: explorer
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: explorer
    serviceName: explorer
    template:
      metadata:
        annotations:
          ad.datadoghq.com/explorer.logs: "[{\n  \"source\": \"ninechronicles-headless\"\
            ,\n  \"service\": \"explorer\",\n  \"log_processing_rules\": [{\n    \"\
            type\": \"exclude_at_match\",\n    \"name\": \"exclude_netmq\",\n    \"\
            pattern\" : \".*\\\\[NetMQTransport\"\n  }]\n}]"
        creationTimestamp: null
        labels:
          app: explorer
          tags.datadoghq.com/env: explorer
          tags.datadoghq.com/version: '1'
        name: explorer
      spec:
        containers:
        - args:
          - NineChronicles.Headless.Executable.dll
          - run
          - --workers=500
          - --app-protocol-version=$(APP_PROTOCOL_VERSION_KEY)
          - --trusted-app-protocol-version-signer=030ffa9bd579ee1503ce008394f687c182279da913bfaec12baca34e79698a7cd1
          - --genesis-block-path=https://release.nine-chronicles.com/genesis-block-9c-main
          - --port=31234
          - --no-miner
          - --store-type=rocksdb
          - --store-path=/data/explorer
          - --ice-server
          - turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us.planetarium.dev:3478
          - --ice-server
          - turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us2.planetarium.dev:3478
          - --ice-server
          - turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us3.planetarium.dev:3478
          - --ice-server
          - turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us4.planetarium.dev:3478
          - --ice-server
          - turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us5.planetarium.dev:3478
          - --peer
          - 027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,9c-main-tcp-seed-1.planetarium.dev,31234
          - --peer
          - 02f164e3139e53eef2c17e52d99d343b8cbdb09eeed88af46c352b1c8be6329d71,9c-main-tcp-seed-2.planetarium.dev,31234
          - --peer
          - 0247e289aa332260b99dfd50e578f779df9e6702d67e50848bb68f3e0737d9b9a5,9c-main-tcp-seed-3.planetarium.dev,31234
          - --graphql-server
          - --graphql-host=0.0.0.0
          - --graphql-port=31235
          - --no-cors
          - --chain-tip-stale-behavior-type=reboot
          command:
          - dotnet
          env:
          - name: DD_ENV
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/env']
          - name: DD_VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/version']
          - name: DD_LOGS_INJECTION
            value: 'true'
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_SERVICE
            value: explorer
          - name: APP_PROTOCOL_VERSION_KEY
            valueFrom:
              configMapKeyRef:
                name: version-config
                key: APP_PROTOCOL_VERSION
          image: planetariumhq/ninechronicles-headless:v100351-1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - /bin/liveness_probe.sh
            failureThreshold: 5
            initialDelaySeconds: 1800
            periodSeconds: 30
            timeoutSeconds: 30
          name: explorer-test
          ports:
          - containerPort: 31235
            name: explorer
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/readiness_probe.sh
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 10
          resources:
            requests:
              cpu: 1300m
              memory: 5Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: explorer-data
          - mountPath: /bin/liveness_probe.sh
            name: probe-script-explorer
            readOnly: true
            subPath: liveness_probe.sh
          - mountPath: /bin/readiness_probe.sh
            name: probe-script-explorer
            readOnly: true
            subPath: readiness_probe.sh
        dnsPolicy: ClusterFirst
        nodeSelector:
          alpha.eksctl.io/nodegroup-name: 9c-main-2xl
          beta.kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 448
            name: reset-snapshot-script
          name: reset-snapshot-script
        - configMap:
            defaultMode: 448
            name: probe-script-explorer
          name: probe-script-explorer
    volumeClaimTemplates:
    - metadata:
        name: explorer-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1000Gi
        storageClassName: gp2-extensible-us-east-2b
        volumeMode: Filesystem
kind: List
metadata:
  resourceVersion: ''
  selfLink: ''
