apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: main-miner-2
    tags.datadoghq.com/env: main-miner-2
    tags.datadoghq.com/version: '1'
  name: main-miner-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-miner-2
  serviceName: main-miner-2
  template:
    metadata:
      annotations:
        ad.datadoghq.com/main-miner-2.logs: "[{\n  \"source\": \"ninechronicles-headless\"\
          ,\n  \"service\": \"main-miner-2\",\n  \"log_processing_rules\": [{\n  \
          \  \"type\": \"exclude_at_match\",\n    \"name\": \"exclude_netmq\",\n \
          \   \"pattern\" : \".*\\\\[NetMQTransport\"\n  }]\n}]"
      labels:
        app: main-miner-2
        tags.datadoghq.com/env: main-miner-2
        tags.datadoghq.com/version: '1'
      name: main-miner-2
    spec:
      containers:
      - args:
        - /app/NineChronicles.Headless.Executable --workers=1000 --app-protocol-version=$(APP_PROTOCOL_VERSION_KEY)
          --trusted-app-protocol-version-signer=03eeedcd574708681afb3f02fb2aef7c643583089267d17af35e978ecaf2a1184e
          --genesis-block-path=https://release.nine-chronicles.com/genesis-block-9c-main
          --host=9c-main-miner-2.planetarium.dev --port=31234 --store-path=/data/miner
          --store-type=rocksdb --no-miner=false --miner-private-key=$(PRIVATE_KEY)
          --peer=027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,9c-main-tcp-seed-1.planetarium.dev,31234
          --peer=02f164e3139e53eef2c17e52d99d343b8cbdb09eeed88af46c352b1c8be6329d71,9c-main-tcp-seed-2.planetarium.dev,31234
          --peer=0247e289aa332260b99dfd50e578f779df9e6702d67e50848bb68f3e0737d9b9a5,9c-main-tcp-seed-3.planetarium.dev,31234
          --graphql-server --graphql-host=0.0.0.0 --graphql-port=80 --sentry-dsn=https://625a444555a547e8822ee86d4f38f046@o195672.ingest.sentry.io/6197051
          --sentry-trace-sample-rate=0.05
        command:
        - /bin/sh
        - -c
        env:
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: miner2
              name: miner-keys
        - name: DD_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: DD_LOGS_INJECTION
          value: 'true'
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_SERVICE
          value: main-miner-2
        - name: APP_PROTOCOL_VERSION_KEY
          valueFrom:
            configMapKeyRef:
              key: APP_PROTOCOL_VERSION
              name: version-config
        image: planetariumhq/ninechronicles-headless:v100350-2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "set -e\nlast_block=\"$(\n  curl \\\n    -H 'Content-Type: application/json'\
              \ \\\n    --data '{\"query\":\"query{chainQuery{blockQuery{blocks(desc:true,limit:1){timestamp}}}}\"\
              }' \\\n    http://localhost:80/graphql \\\n  | jq -r '.data.chainQuery.blockQuery.blocks[0].timestamp'\n\
              )\"\nlast_timestamp=\"$(date +%s -u --date=\"$last_block\")\"\nnow=\"\
              $(date +%s -u)\"\n[[ $(( now - last_timestamp )) -lt 100 ]]\n"
          failureThreshold: 3
          initialDelaySeconds: 1800
          periodSeconds: 30
          timeoutSeconds: 30
        name: main-miner-2
        resources:
          requests:
            cpu: 1300m
            memory: 20Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: main-miner-2-data
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: acr-regcred
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: 9c-main-c5-4xl
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: main-miner-2-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1000Gi
      storageClassName: gp3-extensible
      volumeMode: Filesystem
