apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: main-miner-3
    tags.datadoghq.com/env: main-miner-3
    tags.datadoghq.com/version: '1'
  name: main-miner-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-miner-3
  serviceName: main-miner-3
  template:
    metadata:
      annotations:
        ad.datadoghq.com/main-miner-3.logs: "[{\n  \"source\": \"ninechronicles-headless\"\
          ,\n  \"service\": \"main-miner-3\",\n  \"log_processing_rules\": [{\n  \
          \  \"type\": \"exclude_at_match\",\n    \"name\": \"exclude_netmq\",\n \
          \   \"pattern\" : \".*\\\\[NetMQTransport\"\n  }]\n}]"
      labels:
        app: main-miner-3
        tags.datadoghq.com/env: main-miner-3
        tags.datadoghq.com/version: '1'
      name: main-miner-3
    spec:
      containers:
      - args:
        - /app/NineChronicles.Headless.Executable --workers=1000 --app-protocol-version=$(APP_PROTOCOL_VERSION_KEY)
          --trusted-app-protocol-version-signer=03eeedcd574708681afb3f02fb2aef7c643583089267d17af35e978ecaf2a1184e
          --genesis-block-path=https://release.nine-chronicles.com/genesis-block-9c-main
          --host=9c-main-miner-3.planetarium.dev --port=31234 --store-path=/data/miner
          --store-type=rocksdb --miner-private-key=$(PRIVATE_KEY) --swarm-private-key=$(PRIVATE_KEY)
          --peer=027bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6,9c-main-tcp-seed-1.planetarium.dev,31234
          --peer=02f164e3139e53eef2c17e52d99d343b8cbdb09eeed88af46c352b1c8be6329d71,9c-main-tcp-seed-2.planetarium.dev,31234
          --peer=0247e289aa332260b99dfd50e578f779df9e6702d67e50848bb68f3e0737d9b9a5,9c-main-tcp-seed-3.planetarium.dev,31234
          --graphql-server --graphql-host=0.0.0.0 --graphql-port=80
        command:
        - /bin/sh
        - -c
        env:
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: miner3
              name: miner-keys
        - name: DD_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: DD_LOGS_INJECTION
          value: 'true'
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_SERVICE
          value: main-miner-3
        - name: APP_PROTOCOL_VERSION_KEY
          valueFrom:
            configMapKeyRef:
              key: APP_PROTOCOL_VERSION
              name: version-config
        image: planetariumhq/ninechronicles-headless:v100302
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/liveness_probe.sh
          failureThreshold: 5
          initialDelaySeconds: 1800
          periodSeconds: 30
          timeoutSeconds: 30
        name: main-miner-3
        resources:
          requests:
            cpu: 1300m
            memory: 20Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: main-miner-3-data
        - mountPath: /bin/liveness_probe.sh
          name: probe-script
          readOnly: true
          subPath: liveness_probe.sh
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: acr-regcred
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: 9c-main-c5-4xl
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 448
          name: probe-script
        name: probe-script
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: main-miner-3-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1000Gi
      storageClassName: gp2-extensible
      volumeMode: Filesystem
